name: documentation

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]
    branches: [main]
    paths: [docs/**, .github/workflows/documentation.yml, birdnet_analyzer/cli.py]
  push:
    branches:
      - main
    paths: [docs/**, .github/workflows/documentation.yml, birdnet_analyzer/cli.py]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    env:
      IS_GITHUB_RUNNER: "true"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install .[docs]
      - name: Sphinx build
        run: |
          sphinx-build -E docs _build
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: _build/
          force_orphan: true